GlobalPlanner:
  allow_unknown: false          
  default_tolerance: 0.05        #default
  visualize_potential: false
  use_dijkstra: true               #default is true 
  use_quadratic: true           #default is true 
  use_grid_path: false          #default is false 
  old_navfn_behavior: false     #default is false 

  lethal_cost: 253              #default
  neutral_cost: 50              #default
  cost_factor: 3.0              #default
  publish_potential: true       #default
  orientation_mode: 0           #default
  orientation_window_size: 1    #default
