local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  #static_map: false   
  rolling_window: true       #If static sets true,this param must to set ture
  always_send_full: true    #default is false
  width: 5.0
  height: 5.0
  resolution: 0.05
 

  footprint: [[-0.18, 0.22], [-0.18, -0.22], [0.2425, -0.22], [0.2425,0.22]]

  plugins:
      - {name: static,    type: "costmap_2d::StaticLayer"}
      - {name: sensor,    type: "costmap_2d::ObstacleLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}

  inflation:
      enabled: true
      inflation_radius: 0.10
#cost_scaling_factor: 10
  
  static:
      enabled: true

  sensor:
        observation_sources: laser_scan
        laser_scan: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
